---
title: "Online supplement"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(terra)
library(sf)
library(leaflet)
```

```{r, include=FALSE}
Ps <- rast("./resultater/Picea_sitchensis-epsg3857.tif")
Th <- rast("./resultater/Tsuga_heterophylla-epsg3857.tif")
```

```{r, include=FALSE}
psgbif <- read.delim("./data/0122203-220831081235567/0122203-220831081235567.csv") %>% 
  st_as_sf(coords = c("decimalLongitude", "decimalLatitude"), crs = "EPSG:4326")
psgbif <- psgbif %>% 
  st_transform(crs = crs(Ps)) %>% 
  st_coordinates() %>% 
  rasterize(Ps)

thgbif <- read.delim("./data/0125719-220831081235567/0125719-220831081235567.csv") %>% 
  st_as_sf(coords = c("decimalLongitude", "decimalLatitude"), crs = "EPSG:4326")
thgbif <- thgbif %>% 
  st_transform(crs = crs(Th)) %>% 
  st_coordinates() %>% 
  rasterize(Th)
```

# Sitkagran (*Picea sitchensis*)

```{r, out.width = '100%', warning=FALSE}
domainvals <- range(log10(c(values(Ps$ssp126_2011.2040), 
                            values(Ps$ssp126_2071.2100),
                            values(Ps$ssp370_2071.2100))), na.rm = TRUE)
pal <- colorNumeric(palette = "viridis", 
                    domain = domainvals, na.color = "transparent")

leaflet() %>%
  setView(6.25, 60.9, zoom = 7) %>% 
  addWMSTiles(
    "https://opencache.statkart.no/gatekeeper/gk/gk.open",
    layers = "topo4graatone",
    attribution = "© Kartverket"
  ) %>% 
  addRasterImage(log10(Ps$ssp126_2011.2040), 
                 group = "2011-2040 SSP1-2.6", colors = pal, opacity = 0.5) %>%
  addRasterImage(Ps$ssp126_2011.2040_bin, 
                 group = "2011-2040 SSP1-2.6 (binær)", 
                 colors = c("#440154", "#FDE725"), opacity = 0.5) %>%
  addRasterImage(Ps$ssp126_2011.2040_uncertainty, 
                 group = "2011-2040 SSP1-2.6 usikkerhet", 
                 colors = c("#fee0d2", "#fc9272", "#de2d26"), opacity = 0.5) %>%
  addRasterImage(log10(Ps$ssp126_2071.2100), 
                 group = "2071-2100 SSP1-2.6", colors = pal, opacity = 0.5) %>%
  addRasterImage(Ps$ssp126_2071.2100_bin, 
                 group = "2071-2100 SSP1-2.6 (binær)", 
                 colors = c("#440154", "#FDE725"), opacity = 0.5) %>%
  addRasterImage(log10(Ps$ssp370_2071.2100), 
                 group = "2071-2100 SSP3-7.0", colors = pal, opacity = 0.5) %>%
  addRasterImage(Ps$ssp370_2071.2100_bin, 
                 group = "2071-2100 SSP3-7.0 (binær)", 
                 colors = c("#440154", "#FDE725"), opacity = 0.5) %>%
  addRasterImage(psgbif, group = "GBIF-funn (per oktober 2022)", colors = "black") %>% 
  addLegend(pal = pal, values = domainvals, bins = 5, 
            labFormat = labelFormat(prefix = "10^(", suffix = ") landssnittet 2011-2040"), 
            title = "Klimatisk egnethet") %>% 
  addLayersControl(
    baseGroups = c("2011-2040 SSP1-2.6", "2011-2040 SSP1-2.6 (binær)", "2011-2040 SSP1-2.6 usikkerhet",
                   "2071-2100 SSP1-2.6", "2071-2100 SSP1-2.6 (binær)",
                   "2071-2100 SSP3-7.0", "2071-2100 SSP3-7.0 (binær)"),
    overlayGroups = "GBIF-funn (per oktober 2022)",
    options = layersControlOptions(collapsed = FALSE)
  )
```

# Vestamerikansk hemlokk (*Tsuga heterophylla*)

```{r, out.width = '100%', warning=FALSE}
domainvals <- range(log10(c(values(Th$ssp126_2011.2040), 
                            values(Th$ssp126_2071.2100),
                            values(Th$ssp370_2071.2100))), na.rm = TRUE)
pal <- colorNumeric(palette = "viridis", 
                    domain = domainvals, na.color = "transparent")

leaflet() %>%
  setView(6.25, 60.9, zoom = 7) %>% 
  addWMSTiles(
    "https://opencache.statkart.no/gatekeeper/gk/gk.open",
    layers = "topo4graatone",
    attribution = "© Kartverket"
  ) %>% 
  addRasterImage(log10(Th$ssp126_2011.2040), 
                 group = "2011-2040 SSP1-2.6", colors = pal, opacity = 0.5) %>%
  addRasterImage(Th$ssp126_2011.2040_bin, 
                 group = "2011-2040 SSP1-2.6 (binær)", 
                 colors = c("#440154", "#FDE725"), opacity = 0.5) %>%
  addRasterImage(Th$ssp126_2011.2040_uncertainty, 
                 group = "2011-2040 SSP1-2.6 usikkerhet", 
                 colors = c("#fee0d2", "#fc9272", "#de2d26"), opacity = 0.5) %>%
  addRasterImage(log10(Th$ssp126_2071.2100), 
                 group = "2071-2100 SSP1-2.6", colors = pal, opacity = 0.5) %>%
  addRasterImage(Th$ssp126_2071.2100_bin, 
                 group = "2071-2100 SSP1-2.6 (binær)", 
                 colors = c("#440154", "#FDE725"), opacity = 0.5) %>%
  addRasterImage(log10(Th$ssp370_2071.2100), 
                 group = "2071-2100 SSP3-7.0", colors = pal, opacity = 0.5) %>%
  addRasterImage(Th$ssp370_2071.2100_bin, 
                 group = "2071-2100 SSP3-7.0 (binær)", 
                 colors = c("#440154", "#FDE725"), opacity = 0.5) %>%
  addLegend(pal = pal, values = domainvals, bins = 5, 
            labFormat = labelFormat(prefix = "10^(", suffix = ") landssnittet 2011-2040"), 
            title = "Klimatisk egnethet") %>% 
  addRasterImage(thgbif, group = "GBIF-funn (per oktober 2022)", colors = "black") %>% 
  addLayersControl(
    baseGroups = c("2011-2040 SSP1-2.6", "2011-2040 SSP1-2.6 (binær)", "2011-2040 SSP1-2.6 usikkerhet",
                   "2071-2100 SSP1-2.6", "2071-2100 SSP1-2.6 (binær)",
                   "2071-2100 SSP3-7.0", "2071-2100 SSP3-7.0 (binær)"),
    overlayGroups = "GBIF-funn (per oktober 2022)",
    options = layersControlOptions(collapsed = FALSE)
  )
```
